FROM openjdk:11

ARG JAR_FILE=build/libs/*.jar

#ARG TWITTER_API_KEY=api_key
#ENV TWITTER_API_KEY ${TWITTER_API_KEY}

#ARG TWITTER_API_SECRET=api_secret
#ENV TWITTER_API_SECRET ${TWITTER_API_SECRET}

#ARG TWITTER_ACCESS_TOKEN=access_token
#ENV TWITTER_ACCESS_TOKEN ${TWITTER_ACCESS_TOKEN}

#ARG TWITTER_TOKEN_SECRET=token_secret
#ENV TWITTER_TOKEN_SECRET ${TWITTER_TOKEN_SECRET}

#ARG MONGO_URI=mongo_uri
#ENV MONGO_URI ${MONGO_URI}

COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]